/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.Presentacion;

import com.mycompany.Clases.Propietario;
import com.mycompany.Clases.Turno;
import com.mycompany.Clases.Vehiculo;
import com.mycompany.Persistencias.PropietarioJpaController;
import com.mycompany.Persistencias.TurnoJpaController;
import com.mycompany.Persistencias.VehiculoJpaController;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Nicolay
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextPlaca = new javax.swing.JTextField();
        jTextMarca = new javax.swing.JTextField();
        jTextEstados = new javax.swing.JTextField();
        jButtonInsertar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextAnden = new javax.swing.JTextField();
        jTextDia = new javax.swing.JTextField();
        jTextHora = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextCedulaPlaca = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jButtonVerificarAnden = new javax.swing.JButton();
        jButtonVerificarDia = new javax.swing.JButton();
        jInsertarTurno = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("DATOS DEL CLIENTE: ");

        jLabel2.setText("Nombres:");

        jLabel3.setText("Apellidos:");

        jLabel4.setText("Cedula:");

        jTextCedula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel5.setText("DATOS DEL VEHICULO: ");

        jLabel6.setText("Placa:");

        jLabel7.setText("Marca:");

        jLabel8.setText("Estado:");

        jButtonInsertar.setText("Insertar");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel9.setText("INGRESE DATOS DEL TURNO: ");

        jLabel10.setText("Anden:");

        jLabel11.setText("Dia:");

        jLabel12.setText("Hora:");

        jTextAnden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextAndenActionPerformed(evt);
            }
        });

        jLabel13.setText("Placa:");

        jTextCedulaPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCedulaPlacaActionPerformed(evt);
            }
        });

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel15.setText("BUSCAR INFORMACIÓN");

        jLabel14.setText("- No puede tener 2 turnos en el mismo anden");

        jLabel16.setText("Antes de insertar verifique Anden y Dia");

        jLabel17.setText("- No puede tener 2 turnos en el mismo dia");

        jButtonVerificarAnden.setText("Verificar Anden");
        jButtonVerificarAnden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarAndenActionPerformed(evt);
            }
        });

        jButtonVerificarDia.setText("Verificar Dia");
        jButtonVerificarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerificarDiaActionPerformed(evt);
            }
        });

        jInsertarTurno.setText("Insertar Turno");
        jInsertarTurno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInsertarTurnoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel15)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextCedulaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextEstados, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jTextPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel9))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(jButtonBuscar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(143, 143, 143)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(20, 20, 20))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextAnden, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextDia, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jButtonVerificarDia)
                                            .addComponent(jButtonVerificarAnden)))
                                    .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(62, 62, 62))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jButtonInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jInsertarTurno)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextAnden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jButtonVerificarAnden))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jTextDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonVerificarDia))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextEstados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jButtonInsertar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jInsertarTurno)))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextCedulaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextCedulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCedulaActionPerformed

    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        // TODO add your handling code here:
        String cedula = jTextCedula.getText().trim();
        String nombre = jTextNombre.getText();
        String apellido = jTextApellido.getText();
        String placa = jTextPlaca.getText();
        String marca = jTextMarca.getText();
        String estado = jTextEstados.getText();
        String anden = jTextAnden.getText();
        String dia = jTextDia.getText();
        String hora = jTextHora.getText();

        // Crear entidades
        Propietario propietario = new Propietario();
        propietario.setCedula(cedula);
        propietario.setNombre(nombre);
        propietario.setApellido(apellido);

        Vehiculo vehiculo = new Vehiculo();
        vehiculo.setPlaca(placa);
        vehiculo.setMarca(marca);
        vehiculo.setEstado(estado);
        vehiculo.setPropietario(propietario);

        Turno turno = new Turno();
        turno.setAnden(anden);
        turno.setDia(dia);
        turno.setHora(hora);
        turno.setAuto(vehiculo);

        TurnoJpaController turnoController = new TurnoJpaController();

        // Validar que no tenga turno el mismo día
        if (turnoController.existeTurnoMismoDia(placa, dia)) {
            JOptionPane.showMessageDialog(this,
                    "Este vehículo ya tiene un turno reservado en ese día.");
            return;
        }

        // Validar que no tenga turno en el mismo anden
        if (turnoController.existeTurnoMismoAnden(placa, anden)) {
            JOptionPane.showMessageDialog(this,
                    "Este vehículo ya tiene un turno reservado en ese anden.");
            return;
        }

        // Insertar en BD
        new PropietarioJpaController().create(propietario);
        new VehiculoJpaController().create(vehiculo);
        new TurnoJpaController().create(turno);

        JOptionPane.showMessageDialog(this, "Datos insertados correctamente.");


    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        // TODO add your handling code here:
        String placaIngresada = jTextCedulaPlaca.getText().trim();

        VehiculoJpaController jpaVehi = new VehiculoJpaController();
        Vehiculo vehiculo = jpaVehi.buscarPlaca(placaIngresada);

        if (vehiculo != null) {
            // Obtener propietario
            Propietario propietario = vehiculo.getPropietario();

            // Buscar turnos del vehículo
            TurnoJpaController jpaTurno = new TurnoJpaController();
            List<Turno> turnos = jpaTurno.buscarTurnosPorVehiculo(vehiculo);

            // Construir mensaje
            String mensaje = "Vehículo registrado:\n"
                    + "Placa: " + vehiculo.getPlaca() + "\n"
                    + "Marca: " + vehiculo.getMarca() + "\n"
                    + "Estado: " + vehiculo.getEstado() + "\n\n"
                    + "Propietario:\n"
                    + "Cédula: " + propietario.getCedula() + "\n"
                    + "Nombre: " + propietario.getNombre() + " " + propietario.getApellido() + "\n";

            if (!turnos.isEmpty()) {
                mensaje += "\nTurnos registrados:\n";
                for (Turno t : turnos) {
                    mensaje += "- Día: " + t.getDia() + ", Hora: " + t.getHora() + ", Andén: " + t.getAnden() + "\n";
                }
            } else {
                mensaje += "\nEste vehículo no tiene turnos asignados.";
            }

            JOptionPane.showMessageDialog(this, mensaje);
        } else {
            JOptionPane.showMessageDialog(this, "El vehículo no está registrado.");
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonVerificarAndenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarAndenActionPerformed
        // TODO add your handling code here:
        String placa = jTextPlaca.getText().trim();
        String anden = jTextAnden.getText().trim();

        VehiculoJpaController jpaVehiculo = new VehiculoJpaController();
        Vehiculo vehiculo = jpaVehiculo.buscarPlaca(placa);

        if (vehiculo == null) {
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
            return;
        }

        TurnoJpaController jpaTurno = new TurnoJpaController();
        boolean yaTieneTurnoEnEseAnden = jpaTurno.existeTurnoEnAnden(vehiculo, anden);

        if (yaTieneTurnoEnEseAnden) {
            JOptionPane.showMessageDialog(this, "Este vehículo ya tiene un turno en el andén " + anden + ". No se puede reservar otro.");
        } else {
            JOptionPane.showMessageDialog(this, "El vehículo puede reservar turno en el andén " + anden + ".");
        }


    }//GEN-LAST:event_jButtonVerificarAndenActionPerformed

    private void jButtonVerificarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerificarDiaActionPerformed
        // TODO add your handling code here:
        String placa = jTextPlaca.getText().trim();
        String dia = jTextDia.getText().trim();

        VehiculoJpaController jpaVehiculo = new VehiculoJpaController();
        Vehiculo vehiculo = jpaVehiculo.buscarPlaca(placa);

        if (vehiculo == null) {
            JOptionPane.showMessageDialog(this, "Vehículo no encontrado.");
            return;
        }

        TurnoJpaController jpaTurno = new TurnoJpaController();
        boolean yaTieneTurnoEseDia = jpaTurno.existeTurnoEnDia(vehiculo, dia);

        if (yaTieneTurnoEseDia) {
            JOptionPane.showMessageDialog(this, "Este vehículo ya tiene un turno para el día " + dia + ". No puede reservar otro.");
        } else {
            JOptionPane.showMessageDialog(this, "El vehículo puede reservar un turno para el día " + dia + ".");
        }

    }//GEN-LAST:event_jButtonVerificarDiaActionPerformed

    private void jTextCedulaPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCedulaPlacaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextCedulaPlacaActionPerformed

    private void jTextAndenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextAndenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextAndenActionPerformed

    private void jInsertarTurnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInsertarTurnoActionPerformed
        // TODO add your handling code here:
        String placa = jTextPlaca.getText().trim();
        String anden = jTextAnden.getText().trim();
        String dia = jTextDia.getText().trim();
        String hora = jTextHora.getText().trim();

        VehiculoJpaController jpaVehiculo = new VehiculoJpaController();
        Vehiculo vehiculo = jpaVehiculo.buscarPlaca(placa);

        if (vehiculo == null) {
            JOptionPane.showMessageDialog(this, "El vehículo no está registrado.");
            return;
        }

        TurnoJpaController jpaTurno = new TurnoJpaController();

        boolean mismoAnden = jpaTurno.existeTurnoEnAnden(vehiculo, anden);
        boolean mismoDia = jpaTurno.existeTurnoEnDia(vehiculo, dia);

        if (mismoAnden) {
            JOptionPane.showMessageDialog(this, "Este vehículo ya tiene un turno en el anden " + anden + ".");
            return;
        }

        if (mismoDia) {
            JOptionPane.showMessageDialog(this, "Este vehículo ya tiene un turno para el día " + dia + ".");
            return;
        }

        // Crear y guardar el nuevo turno
        Turno turno = new Turno();
        turno.setAnden(anden);
        turno.setDia(dia);
        turno.setHora(hora);
        turno.setAuto(vehiculo);

        jpaTurno.create(turno);
        JOptionPane.showMessageDialog(this, "Turno reservado correctamente.");
    }//GEN-LAST:event_jInsertarTurnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JButton jButtonVerificarAnden;
    private javax.swing.JButton jButtonVerificarDia;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JButton jInsertarTurno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextAnden;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextCedulaPlaca;
    private javax.swing.JTextField jTextDia;
    private javax.swing.JTextField jTextEstados;
    private javax.swing.JTextField jTextHora;
    private javax.swing.JTextField jTextMarca;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPlaca;
    // End of variables declaration//GEN-END:variables
}
